apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-admin-externalsecret.yaml
  - lab-api-alerts.yaml
configMapGenerator:
  - name: lab-api-dashboard
    files:
      - dashboards/lab-api.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
