apiVersion: v1
kind: Namespace
metadata:
  name: lab-app
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    elbv2.k8s.aws/pod-readiness-gate-inject: enabled
