apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lab-api-secrets
  namespace: lab-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: lab-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: CHAOS_TOKEN
      remoteRef:
        key: cloud-lab-platform/dev/chaos-token
